### ISSUE TITLE
When to use this library vs angular-in-memory-web-api

### ISSUE THREAD

**Issue by christianacca** [ovotech/data-mocks#45]
[This article](https://medium.com/@amcdnl/mocking-with-angular-more-than-just-unit-testing-cbb7908c9fcc) describes using angular-in-memory-web-api. Potentially extending it with faker.js

If my app is an angular app, what use case makes sense to use data-mocks instead of angular-in-memory-web-api?

thanks
Christian

**Comment by grug** [comment]
Hey @christianacca - happy new year!

I've just taken a look through `angular-in-memory-web-api` and can offer my thoughts :)

They achieve a pretty similar goal - they both intercept HTTP requests before they're made and give back canned responses.

I think the advantages of `data-mocks` (compared to `angular-in-memory-web-api`) are:
- quicker and easier to setup
- it's framework agnostic
- scenario support
- it's a smaller package
- mocks have a simpler/clearer interface (that one is subjective)
- smaller memory footprint

Don't get me wrong, though - `angular-in-memory-web-api` has plenty of advantages too - as it operates like a db, so you can mutate your mocks which is very handy.

The use case I can see where `angular-in-memory-web-api` is preferable to use over `data-mocks` is when you need to replicate the effects of persisting data across pages that has changed since you received the mock for it _where you aren't maintaining it in local state_. Also, you wouldn't want to use data-mocks in a unit test environment, whereas it looks like you could do that nicely with `angular-in-memory-web-api`. Other than these two things, I think `data-mocks` is a more sensible choice :)

Hope that helps - happy to discuss further if you like - or over a beer/coffee if you find yourself in London :)

**Comment by grug** [comment]
@christianacca I'll close this for now, but please feel free to comment/reopen :)
